### ISSUE TITLE
Issues, update, and contact questions

### ISSUE THREAD

**Issue by daedaevibin** [BlissRoms/stable_releases#1] opened 2024-11-17 11:27 UTC
1: please make a discord or something. Instagram isn't used, the original discord is no longer used either, and I'm entirely incapable of using Telegram no matter what I do. In doing so, I'm stuck resorting to this for contact

2: When Will A15 (Android 15) releases be expected? More specifically for the Pixel 6a (BlueJay). It is totally fine if there's no specific date at this time.

3:it has trouble handling custom launchers, icons and such. Extreme overheating problems as well. Maybe look into that?

**Comment by StudioKeys** [comment] 2024-11-20 03:33
If u cant use Telegram, then its more of a you issue, than be on us.
We dont have the time to sit on both Telegram and Discord both altogether.

Secondly, u came here for a ETA for a device, which is not acceptable and ur query for that will remain unanswered

Thirdly, the issues u mention are something thats not faced on our end, so im closing this up

**Closed as completed by StudioKeys** 2024-11-20 03:33 UTC

**Comment by daedaevibin** [comment] 2024-11-20 06:25
> If u cant use Telegram, then its more of a you issue, than be on us.
> We dont have the time to sit on both Telegram and Discord both altogether.
> 
> Secondly, u came here for a ETA for a device, which is not acceptable and ur query for that will remain unanswered
> 
> Thirdly, the issues u mention are something thats not faced on our end, so im closing this up

1: testing is needed to confirm anything.

2: it is not stated in any way shape or form that i am not allowed to ask certain questions anywhere that I can find.

3: issues are still issues. If you've heard of them before, you should say what you know and not ignore it.

4: System UI crashes repeatedly, the entire theme engine fails, and I'm also stuck with a blue color scheme which is not what I have set but this issue also exist in stock android 14 for the device and may not be easily fixed, or fixed at all.

**Comment by StudioKeys** [comment] 2024-11-20 08:25
1. I'm the maintainer of the mentioned device i.e., Pixel 6a which i have been using as my primary device up until last week until its USB port decided to give up on me and i never faced the issues you have mentioned.

2. The GitHub pinned repos has something known as an issue_tracker which is used for raising issues even as this repo is used as a manifest and not some sort of bug tracker. Pls. read twice before performing actions.

3. The issues that u state are something that aint faced by myself or any of my users. I'm all open to user feedback on Telegram groups and try to fix it with every releases as at the end of day, i'm also a user of what i create.

4. Again, none faced by anyone so the issue is on your end, and we cant do nothing about it. Every releases has its notes mentioned like for every QPR, its specifically mentioned to clean flash because Google changes the code-bases for which whatever we did prior to QPR is needed to be rebased upon fresh codebase.

The fourth mentioned issue can arise if u dirty flash across QPRs, also try to use the proper repo for raising issues even.

Cheers,
StudioKeys

**Comment by daedaevibin** [comment] 2024-11-20 16:44
> 1. I'm the maintainer of the mentioned device i.e., Pixel 6a which i have been using as my primary device up until last week until its USB port decided to give up on me and i never faced the issues you have mentioned.
> 
> 2. The GitHub pinned repos has something known as an issue_tracker which is used for raising issues even as this repo is used as a manifest and not some sort of bug tracker. Pls. read twice before performing actions.
> 
> 3. The issues that u state are something that aint faced by myself or any of my users. I'm all open to user feedback on Telegram groups and try to fix it with every releases as at the end of day, i'm also a user of what i create.
> 
> 4. Again, none faced by anyone so the issue is on your end, and we cant do nothing about it. Every releases has its notes mentioned like for every QPR, its specifically mentioned to clean flash because Google changes the code-bases for which whatever we did prior to QPR is needed to be rebased upon fresh codebase.
> 
> The fourth mentioned issue can arise if u dirty flash across QPRs, also try to use the proper repo for raising issues even.
> 
> Cheers,
> StudioKeys 

Then my apologies if I seemed rude.

And I did clean flash to what was possible even though I was forced to extract the payload.hin to even get the image files to be able to flash to begin with since no matter where I looked I could not find them anywhere at all. It would be nice if the img files were also uploaded so I didn't have to extract them myself.

**Comment by StudioKeys** [comment] 2024-11-26 09:17
Bliss v18.0 based on Android 15 for Bluejay was released earlier today or yesterday.
You could try that.

Cheers,
StudioKeys

**Comment by daedaevibin** [comment] 2024-11-26 21:45
Yes, I just got it. I'm in a bit of a predicament now though.

The options for changing the style (mine is set to cyberpunk) for the quick settings menu is gone. Or at least I can't find it anywhere at all no matter where I look. What do I do? It's causing my accent colors to include blue as one of them, it's very troublesome.

I just add, I keep recieving an app crash message. com.android.hbmsvmanager I believe. If I close it before my launcher loads on the home screen, the phone restarts.

![Screenshot_20241126-154601_GitHub.png](https://github.com/user-attachments/assets/1cf925b9-09f6-483b-8277-3b90aafae497)
